[tools]
node = "lts"
"npm:@earendil-works/pi-coding-agent" = "latest"
"github:kunchenguid/treehouse" = "latest"
"npm:gh-axi" = "latest"
"npm:chrome-devtools-axi" = "latest"
"npm:lavish-axi" = "latest"
"npm:tasks-axi" = "latest"
"npm:quota-axi" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
